### ISSUE TITLE
Minor changes to default `index.html` that should be viewable when running `yarn dev` at http://localhost:6001/

### ISSUE THREAD

**Issue by himerus** [phase2/outline-templates#3]
Minor changes to default `index.html` that should be viewable when running `yarn dev` at http://localhost:6001/

_Originally posted by @himerus in https://github.com/phase2/outline-templates/pull/2#pullrequestreview-2001061148_

**Comment by jardix22** [comment]
This issue was fixed in the pull request #4

**Comment by jardix22** [comment]
This issue was fixed in the pull request #4
